# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 05:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import micasite.custom_classes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, micasite.custom_classes.SerializerMixin),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True, unique_for_date=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, unique_for_date=True)),
            ],
            bases=(models.Model, micasite.custom_classes.SerializerMixin),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(models.Model, micasite.custom_classes.SerializerMixin),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(to='store.Category')),
            ],
            bases=(models.Model, micasite.custom_classes.SerializerMixin),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message=b"phone number must be entered in the format: '+999999999'", regex=b'^\\+?1?\\d{9,15}$')])),
                ('date_joined', models.DateField()),
            ],
            bases=(models.Model, micasite.custom_classes.SerializerMixin),
        ),
        migrations.AddField(
            model_name='size',
            name='sub_category',
            field=models.ManyToManyField(to='store.SubCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.SubCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Vendor'),
        ),
    ]
