# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendory',
            new_name='vendor',
        ),
    ]
