# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.Category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
