# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 12:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import micasite.custom_classes


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20160308_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message=b"phone number must be entered in the format: '+999999999'", regex=b'^\\+?1?\\d{9,15}$')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            bases=(models.Model, micasite.custom_classes.SerializerMixin),
        ),
    ]
