# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(b'Pe', b'Pending'), (b'Pr', b'Processed'), (b'Sh', b'Shipped'), (b'Rec', b'Received'), (b'Re', b'Returned')], default=b'Pe', max_length=3),
        ),
    ]
