# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20160312_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_sold',
            field=models.DateField(),
        ),
    ]
